### ISSUE TITLE
License ShareAlike requirements

### ISSUE THREAD

**Issue by OscarAbraham** [prime31/CharacterController2D#102]
Hi, I understand by reading [this issue](https://github.com/prime31/CharacterController2D/issues/83) that the license addendum allows for commercial games. There's something that's not very clear to me, though: does the ShareAlike requirement still apply for games? In other words: Are games that use this CharacterController2d required to be shared with a CC BY/NC/SA license? Thanks.

**Comment by prime31** [comment]
Absolutely not. Use it in any and all games you want to use it in. The only restriction is selling it as part of a game asset.
