### ISSUE TITLE
inconsistent grounding detection

### ISSUE THREAD

**Issue by PaperMartin** [prime31/CharacterController2D#106]
making a 2d character and for some reason half the time the character is on the ground, it doesn't detect said ground, completely randomly. as in, the character could be standing on a static ground, not moving, and 1 frame isgrounded might be true and the next it might be false
example of "isgrounded" being checked every frame
![kndmylerCL](https://user-images.githubusercontent.com/39214593/76700905-71f52f00-66bc-11ea-9117-6dd03c4b5966.gif)
happened in multiple of my projects, regardless of if the movement & checking happens in update or fixed update,regardless of the amount of horizontal and vertical rays, and regardless of if the rigidbody is discrete or continuous
edit : fixed the issue by continously moving the character toward the ground, even if he's grounded

**Comment by myamk** [comment]
I'm experiencing the same issue after updating from Unity 2018 to 2019. Weirdly enough, this happens only in Unity's preview but when I build and run the project it works as good as before.

**Comment by myamk** [comment]
BTW if anyone interested, I got rid of this issue by changing RigidBody2D's parameters: **_Collision Detection_** to **Discrete** and **_Interpolate_** to **Extrapolate**.

**Comment by juliano7s** [comment]
I was having this issue and I think I figured out why. The problem happens when you pass a (0,0) vector to `move()`. The `collisionState` is reset, but no movement function is called, which results in `collisionState.below = false`. Then, once you move down again, it collides with ground and changes it to true.

**Comment by juliano7s** [comment]
> I was having this issue and I think I figured out why. The problem happens when you pass a (0,0) vector to `move()`. The `collisionState` is reset, but no movement function is called, which results in `collisionState.below = false`. Then, once you move down again, it collides with ground and changes it to true.

Maybe the fix is to only reset the `collisionState` on `move()` if the `deltaMovement != (0,0,0)`
