### ISSUE TITLE
[Question] License Clarification

### ISSUE THREAD

**Issue by darkevilmac** [prime31/CharacterController2D#42]
Hello, recently I discovered this CharacterController and it seems like it would suit my needs really well. However, when I read the license I'm just having a slight misunderstanding. My question is would it be within the bounds of your license to use your controller in a non free game I'm making?

**Comment by csotomon** [comment]
Corgi Engine
https://www.assetstore.unity3d.com/en/#!/content/26617 is selling your code (with modifications) in that asset.

they have a class called CorgiController2D and the code is 80% equal to CharacterController2D.

**Comment by prime31** [comment]
Many thanks for the heads up. I will report it directly to Unity.


Mike

**Comment by mrcoder16** [comment]
To further expand and clarify on this topic, after creating a closed source game using the CharacterController will I then have to release my personal code that builds open or uses the CharacterController? Also in terms of attribution would putting it in the Credits portion of the game be sufficient or even necessary?

**Comment by prime31** [comment]
When using the CC2D in a game nothing at all needs to be done. No attribution is required and you most certainly don't need to release your source code. You are clear to just make all your games with it!

Mike


On Mar 6, 2015, at 12:08 AM, mrcoder16 <notifications@github.com> wrote:

To further expand and clarify on this topic, after creating a closed source game using the CharacterController will I then have to release my personal code that builds open or uses the CharacterController? Also in terms of attribution would putting it in the Credits portion of the game be sufficient or even necessary?

**Comment by mrcoder16** [comment]
Thank you for the quick reply and the awesome CharacterController.
