### ISSUE TITLE
Can't ascend low hanging one-way platforms, possible fix included

### ISSUE THREAD

**Issue by astrobread** [prime31/CharacterController2D#43]
If a one-way platform is placed just overhead of the character, they cannot jump completely through it.

To recreate place a one-way platform just above the player. They don't need to be touching, but it has to be close enough so that the initial jump velocity will collide them in the first frame of the jump.

Expected result is that the player passes through the one-way platform, then lands on it after the jump is complete. Observed result is that the player travels most of the way through the platform, then their jump ends much sooner than expected and they fall back to where they started.

![onewayjumpsnap](https://cloud.githubusercontent.com/assets/8303758/5604181/606c6696-9371-11e4-8000-2a6e8aedf0da.PNG)

This issue can be resolved by modifying this line in CharacterController2D.moveVertically:
```
if (isGoingUp && !collisionState.wasGroundedLastFrame)
   mask &= ~oneWayPlatformMask;
```

If you remove the wasGroundedLastFrame condition the platform behaves as expected. Was this condition included to allow one-way platforms with slopes? Or is it for something else I'm not aware of?

**Comment by prime31** [comment]
That change was indeed a way to allow walking up a sloped one-way platform.
I'll have to give it some though to see if there is a clean way to handle
both or if sloped one-way platform support should be a boolean
configuration (seems like it is not very common).


Mike

**Comment by astrobread** [comment]
This is just from eyeballing the code so I could be missing something, but I don't think this change would impact one-way platform slopes.

There are no meaningful collisions with one-way platforms while ascending in MoveVertically(). It only casts rays from the top of the collider in this situation, so anything it hits has nothing to do with what you're walking across. When ascending, this function's only job is to prevent you from cracking your head against solid platforms.

What makes sloped one-way platforms work is already inside MoveHorizontally(), which uses similar logic to detect slopes from either kind of platform. Whereas the grounded check inside MoveVertically() only seems to prevent jumping onto one-way platforms

**Comment by prime31** [comment]
You might be right. I'll do some rest with and without the check and make sure all is well.


On Jan 4, 2015, at 4:50 PM, astrobread <notifications@github.com> wrote:

This is just from eyeballing the code so I could be missing something, but I don't think this change would impact one-way platform slopes.

There are no meaningful collisions with one-way platforms while ascending in MoveVertically(). It only casts rays from the top of the collider in this situation, so anything it hits has nothing to do with what you're walking across. When ascending, this function's only job is to prevent you from cracking your head against solid platforms.

What makes sloped one-way platforms work is already inside MoveHorizontally(), which uses similar logic to detect slopes from either kind of platform. Whereas the grounded check inside MoveVertically() only seems to prevent jumping onto one-way platforms
