### ISSUE TITLE
primeRaycastOrigins incorrectly shaping raycastOrigins

### ISSUE THREAD

**Issue by astrobread** [prime31/CharacterController2D#44]
The first and final raycasts should be positioned `_skinWidth` away from their respective sides. Instead, the first raycast is too close and the last one is too far away. This can cause unexpected behavior depending on which direction you are traveling. Going uphill to the right is especially more prone to having issues when dealing with slopes.

![verticalrays](https://cloud.githubusercontent.com/assets/8303758/5625308/0da6f1dc-953e-11e4-95f7-4ace65ae6ecd.PNG)

The problem is caused by primeRaycastOrigins() at this line: `modifiedBounds.Expand( -_skinWidth );` This function reduces the total width and height by _skinWidth, or to put another way cuts off half of _skinWidth from every corner. This needs to doubled, similar to how recalculateDistanceBetweenRays() currently works, like this: `modifiedBounds.Expand( -2f * _skinWidth );`

**Comment by prime31** [comment]
Good spot. I just pushed out an update with the fix.
