### ISSUE TITLE
Descending from OneWayPlatform

### ISSUE THREAD

**Issue by wyemun** [prime31/CharacterController2D#45]
In some games, which allows player to jump-down / descend (usually by pressing down + jump).

The way which I have implemented such functionality is by adding a new optional arg to:
```
private void moveVertically( ref Vector3 deltaMovement, bool descend = false ) {
```
and in the same method
```
if(descend)
    mask &= ~oneWayPlatformMask;
```

The *descend* boolean will be flagged as true whenever the player trigger the down+jump combo.

I wonder if there's any better way to implement this?

**Comment by prime31** [comment]
That sounds like a perfectly fine way to handle the situation.


Mike
