### ISSUE TITLE
Falling through diagonal one-way platforms

### ISSUE THREAD

**Issue by iainlobb** [prime31/CharacterController2D#46]
One-way platforms seem to work great if they're flat, but if you rotate one to e.g. a 45 degree angle and then jump onto it from the side, you will often (but not always) pass right through.

Thanks for the library btw (and Trashman).

**Comment by snugsound** [comment]
I'm encountering this issue as well. Were you able to find a solution?

**Comment by iainlobb** [comment]
Urgh - sorry, no - I gave up on this library and implemented all my player physics using Unity's built in 2D physics - which now includes support for 1-way platforms. It was a lot of work to make the switch but I'm glad I did - now I can interact with any physics-driven elements, e.g. moving platforms

**Comment by snugsound** [comment]
@prime31 any plans to look at this one, or offhand suggestions for a possible fix I might attempt to implement myself?
