### ISSUE TITLE
Character Moving through above tile if going up slope.

### ISSUE THREAD

**Issue by grtoth** [prime31/CharacterController2D#48]
![capturar](https://cloud.githubusercontent.com/assets/3420694/6922468/b98e89e2-d7a1-11e4-9c4c-895036f1b84b.PNG)

If you have a situation like this and keep moving up in the slope, the character "ignore" the above collision.

I "fixed" that by adding this. (ps: don't know if is the "right" way of doing this)

![capturar1](https://cloud.githubusercontent.com/assets/3420694/6922509/0713774a-d7a2-11e4-8e25-e16621f6cd1c.PNG)

Thanks for the awesome script!

**Comment by anhTD93** [comment]
Great stuff, I'm having the same problem bugging me all the way. Gonna take a look on your solution. Thanks :+1:
