### ISSUE TITLE
Weird motion when player get stuck inside blocks 

### ISSUE THREAD

**Issue by itsjef** [prime31/CharacterController2D#49]
![untitled](https://cloud.githubusercontent.com/assets/1902587/6977469/f134f104-d9e7-11e4-9e6b-56ee2be8d1ea.png)

If you have a situation like this, when the Black player get stuck inside platform, it will slowly rise up until standing on the top-most block. I don't get it at all so if you can guide my through this problem I'll be very appreciated. 

*Edit: Collider on those blocks the player got stuck in is BoxCollider2D

**Comment by nicloay** [comment]
I have the same problem, did you try to reduce skin width ?

**Comment by anhTD93** [comment]
I did, but it does not really solve the problem, just make the rising up much slower.

Debug.Log while the black one is stuck with no input:
> _[CharacterCollisionState2D] r: False, l: False, a: **False**, b: **True**, movingDownSlope: False, > angle: 0, wasGroundedLastFrame: True, becameGroundedThisFrame: False_

And when i press Jump:
> _[CharacterCollisionState2D] r: False, l: False, a: **True**, b: **False**, movingDownSlope: False, > angle: 0, wasGroundedLastFrame: True, becameGroundedThisFrame: False_

Although the player is stuck, _collisionState_ only points out whether it's colliding **_below_**, another thing is while the player is actually still rising but **_isGoingUp_** return **false** so the else condition in

`
if( isGoingUp ) {...}
else {
    **deltaMovement.y += _skinWidth;**
    collisionState.below = true;
}
` 

is called.

So I think the solution is to either deal with the RayCasting or the if-else condition. Hope you can figure out one soon.

**Comment by jamiltron** [comment]
What are the colliders on those blocks? Edge colliders?

**Comment by nicloay** [comment]
i have just boxcollider2d

**Comment by anhTD93** [comment]
mine is also BoxCollider2D, these blocks' layer is set to Platform Mask too.

**Comment by nicloay** [comment]
i've just come up to the same problem again.
If you don't have slopes, as workaround you can try set slope limit to zero.
