### ISSUE TITLE
Character snaps to ground when dropping onto sloped surfaces.

### ISSUE THREAD

**Issue by tmunro** [prime31/CharacterController2D#50]
When using the CharacterController2D to move a character along angled platforms, the character will snap to the ground when moving down onto a sloped surface that is sloped down in the direction of movement if the surface is within the distance defined by the `slopeCheckRayDistance`.
![screenshot 2015-04-30 13 58 08](https://cloud.githubusercontent.com/assets/3076428/7422856/0f6d5cde-ef45-11e4-8129-38d1ef756fd5.png)

My game makes extensive use of lightly sloped surfaces, and disabling the snap-to-ground feature entirely makes moving down longer slopes (especially moving quickly) prone to problems. Not sure what a good solution would be.

**Comment by prime31** [comment]
CC2D snaps on slopes by default. To change that behavior you will need to modify the handleVerticalSlope method to accommodate the specific feel you are looking for.

**Comment by tmunro** [comment]
I should have included this at the beginning - is this kind of drop-snap the expected behavior?

![slopedrop](https://cloud.githubusercontent.com/assets/3076428/7424887/29bfadfa-ef5c-11e4-84f4-72af54256549.gif)

**Comment by prime31** [comment]
When a sloped surface is below snapping will occur by default. You can modify the Ray distance used for slope detection to be as small or large as you would like to get the exact feel you want. See the _slopeLimitTangent ivar for all code that deals with slopes and snapping.
