### ISSUE TITLE
Character smooths before landing

### ISSUE THREAD

**Issue by Cactuar1** [prime31/CharacterController2D#54]
I can't recall if this happened pre-Unity5, but when the character lands from a jump it smooths towards the ground.
You can replicate this by simply turning the camera follow script off and jumping,
![memem](https://cloud.githubusercontent.com/assets/5230222/8149509/75a6f5aa-12bd-11e5-9e68-0c9fbfda9818.gif)

ta

**Comment by prime31** [comment]
That sure does look like a case of RigidBody kinematics gone wrong! I just pushed an update that has the RigidBody settings fixed and should solve the problem for you.
