### ISSUE TITLE
How to interact with physic world from a non-physic world?

### ISSUE THREAD

**Issue by aidinzolghadr** [prime31/CharacterController2D#60]
Hi,
There are parts in the my game that when my CC2D character that is not simulated by physics needs to for example push a physically simulated object. What's the best approach to do so?

Thanks

**Comment by prime31** [comment]
You would do this the same exact way as if you were using the standard CharacterController: just apply forced to any physics objects that you want to interact with. 

Mike


On Aug 1, 2015, at 3:12 AM, Aidin Zolghadr <notifications@github.com> wrote:

Hi,
There are parts in the my game that when my CC2D character that is not simulated by physics needs to for example push a physically simulated object. What's the best approach to do so?

Thanks

**Comment by aidinzolghadr** [comment]
Would you please elaborate more on this? For example there are sprites with attached rigibody2D's and boxCollider2D's that I want my player to be able to push around. If I put that object to Platform layer, it will be immovable or I'm missing something here.
