### ISSUE TITLE
[Cancel] My Mistake

### ISSUE THREAD

**Issue by McGunn** [prime31/CharacterController2D#61]
So sorry. This question was for a different controller on a different github page. This was very dumb of me.

**Comment by prime31** [comment]
None of what you wrote makes any sense in the context of the CharacterController2D script. None of the classes or methods you describe exist in the CharacterController2D.

Mike


On Aug 7, 2015, at 11:24 PM, McGunn <notifications@github.com> wrote:

I'm working on a game that requires there to be moving entities or objects that act as moving platforms. But those entities need to also be affected by moving platforms like the player is. This means that the player could toss a stack of boxes onto a moving platform, and the stack will all just move along nicely.

So technically this means that these entities need to be in the MovingPlatform layer. When I move them into that layer they detect themselves for collisions and just float in the air basically unable to move anywhere. (Right now I'm using the Simple AI Ninjas to test this)

I've tried going through the PlatformerMotor2D script and doing a little trick. I switch the layer to a new layer that I called TempLayer. Run all the checks, and then switch back to the original layer. This now makes the characters stay in a falling state and technically causes their vertical speed to increase(unlike before when they would stand in the air) but they still do not fall, and seem to be detecting a collision with themselves.

I'll write down where I do the layer switching trick in case someone knows of a place where I missed it:

I'm switching the layer to TempLayer and Back to moving Platform at the start and end of:
private CollidedSurface CheckSurroundings(bool forceCheck)
and
private void CheckWallInteractionValidity()

Thanks.

Curt
