### ISSUE TITLE
Replacing raycast with boxcasts?

### ISSUE THREAD

**Issue by sponge** [prime31/CharacterController2D#73]
Does it make any sense to replace the multiple raycasts with a single boxcast? My understanding is that boxcasts were added sometime during Unity 4 dev, after CC2D was first made. My attempt to replace the individual raycasts with a single boxcast did not go so well first attempt, but I've also refactored things a bit to ignore self-collisions in the raycasts, so maybe I broke something else. Thanks for the great work, otherwise!

**Comment by prime31** [comment]
My experiments with boxcasts didn't go so well. Too many edge cases cropped up and there was no performance improvement so it wasn't worth committing to the repo.
