### ISSUE TITLE
Problem with Unity 5.5.0.f3's Rigidbody 2D

### ISSUE THREAD

**Issue by aidinzolghadr** [prime31/CharacterController2D#77]
Hi,

First of all, I've used this fantastic character controller before several times so I'm not new to it. But when I tried it today with Unity 5.5, it doesn't work anymore. It just goes through all objects, even ones set in Platform mask (that is also set in CC2D's corresponding section.).

My best guess is the changes in Rigidbody 2D that happened sometime in recent versions because looks of it is different and I see new features on it than what it used to be before. (Been away from Unity for some time so I can't know for sure the differences.)

I've tried plaing with Rigidbody2D's values but I can't get it to work.

Thanks!

**Comment by christophe-h-mary** [comment]
Hi !
Could it be because of the new kinematic options ?
You could try checking simulated and use full kinematic contacts.
That's how my character is configured.

**Comment by aidinzolghadr** [comment]
Yes you are right, I'm an absolute idiot.
