### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by rickystewart** [prime31/CharacterController2D#79]
Here's the license segment of the README right now:

> Attribution-NonCommercial-ShareAlike 3.0 Unported with simple explanation. You are free to use the CharacterController2D in any and all games that you make. You cannot sell the CharacterController2D directly or as part of a larger game asset.

But the text of the license contradicts the clarifications.  As written, the license forbids the use of CharacterController2D in any commercial project.  *However*, the sentence "you are free to use the CharacterController2D in any and all games that you make" suggests that commercial projects might be OK.

This sentence should probably be reworded to not sound so permissive, unless this asset can be used with commercial projects, in which case a different license should probably be selected.

**Comment by prime31** [comment]
All of our open source code is Attribution-NonCommercial-ShareAlike 3.0 with the additional clause that you are most definitely allowed to use them in your commercial games. The only restriction is that you cannot include them in any game assets.
