### ISSUE TITLE
primeRayCastOrigins(): parameters in its summary

### ISSUE THREAD

**Issue by OldAmnis** [prime31/CharacterController2D#81]
Not sure if here is the right place to ask this.

As I'm studying your code to understand raycasting, I stumbled upon the following summary for primeRayCastOrigins():
```
/// <summary>
/// resets the raycastOrigins to the current extents of the box collider inset by the skinWidth. It is inset
/// to avoid casting a ray from a position directly touching another collider which results in wonky normal data.
/// </summary>
/// <param name="futurePosition">Future position.</param>
/// <param name="deltaMovement">Delta movement.</param>
```

However, the method has no parameters. Were futurePosition and deltaMovement leftovers from older versions, or perhaps I'm missing something?

Thanks.

**Comment by prime31** [comment]
Those two XML comment bits are just remnants from the older version of the method.
