### ISSUE TITLE
License

### ISSUE THREAD

**Issue by petersvp** [prime31/CharacterController2D#83]
CC BY/NC/SA forbids using this in commercial games.... Is it really intended, or you intend we to use this code only as a reference to roll our own solutions?

**Comment by prime31** [comment]
The license is Attribution-NonCommercial-ShareAlike 3.0 with the addendum:

> You are free to use the CharacterController2D in any and all games that you make. You cannot sell the CharacterController2D directly or as part of a larger game asset.

You are free and clear to use it in games commercial or not.
