### ISSUE TITLE
[Question] License Clarification

### ISSUE THREAD

**Issue by paulrayrussell** [prime31/CharacterController2D#89]
I realise that this was asked two years ago, but can I check that use of the controller in binary format in a sold for profit game is still ok? Don't know if I'll sell many copies, but I would like to check. The simple explanation says otherwise. I quote "NonCommercial — You may not use the material for commercial purposes." Thanks.

**Comment by paulrayrussell** [comment]
I quote "NonCommercial — You may not use the material for commercial purposes."

**Comment by prime31** [comment]
You can absolutely use the code in any released, commercial games. You cannot use the code as part of an asset pack though.

**Comment by paulrayrussell** [comment]
Thanks for But the license doesn't say this: "You may not exercise any of the rights granted to You in Section 3 above in any manner that is primarily intended for or directed toward commercial advantage or private monetary compensation." It's a non-commercial license. It's even entitled as non-commercial.

**Comment by prime31** [comment]
There is an addendum to the license stated in the README waving the non-commercial clause:

> You are free to use the CharacterController2D in any and all games that you make. You cannot sell the CharacterController2D directly or as part of a larger game asset.

**Comment by paulrayrussell** [comment]
Might I suggest - even then you are not specifically saying this overrides anything in the other license.
"You are free to use the CharacterController2D in any and all games that you make including commercial games but you cannot sell the CharacterController2D directly or as part of a larger game asset."
I understand your position, this doesn't really quite fit under LGPL with CPE as it would require users to make available your source with their solutions, but the LGPL would seem a closer fit that your current non-commercial license.

**Comment by paulrayrussell** [comment]
Sounds like a good idea. Please let me know if you post one - if it's timely, I'll buy a copy.
