### ISSUE TITLE
when you run and jump it can push you back when you hit the floor or the ground

### ISSUE THREAD

**Issue by yoskeleton** [prime31/CharacterController2D#95]
Hello,

when you run and jump it can push you back when you hit the floor or the ground

when i increase the skinWidth value the issue appear more often it should be something related to that 

is this a know issue or i did something wrong? 

i can try to make a video of the issue if needed

**Comment by louisgjohnson** [comment]
I've noticed this as well, I'm going to investigate it soon and see if I can find a solution
